title: l1nc ctf
description: Newbies that want to learn.
encoding: UTF-8
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

# needed for jekyll-sitemap generator
url: "https://l1ncctf.github.io" 

# logo
avatar: /assets/images/jekyll-logo.svg

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
